name: CI/CD Pipeline Basic

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    - name: Install dependencies and run tests
      run: |
        cd sistem-ci-cd-basic/meu-app-express
        npm install
        npm test
    - name: Deploy to Staging
      if: github.ref == 'refs/heads/main'
      run: |
        cd sistem-ci-cd-basic/meu-app-express
        echo "Deploying to staging environment"
      # Adicione aqui os comandos para deploy, dependendo do seu ambiente de staging.
