name: CI/CD Pipeline Básico

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Configurar Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Instalar dependências
      run: npm install
      working-directory: meu-app-express

    - name: Imprimir versão do Node.js
      run: node -v

    - name: Imprimir versão do NPM
      run: npm -v

    - name: Listar pacotes NPM instalados
      run: npm list

    - name: Instalar jest-html-reporter
      run: npm install jest-html-reporter --save-dev
      working-directory: meu-app-express

    - name: Executar testes
      run: npm test
      working-directory: meu-app-express

    - name: Carregar Relatório de Testes como Artefato
      uses: actions/upload-artifact@v2
      with:
        name: test-report
        path: meu-app-express/test-report.html
